# Generated by Django 6.0.4 on 2026-04-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('published_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.FloatField()),
                ('sell_rate', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.currency')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='forex.exchangerateday')),
            ],
            options={
                'unique_together': {('day', 'currency')},
            },
        ),
    ]
